import { TravelInsurance,Scooter,CourierServices,Message,PremiumLounge,ProfileIconBox, ClanderIcon1, ClanderIcon2, Holidays, WeeklyIcon } from './Image';

import { scale } from './responsive';

export const visaOptions = [
   { id: '1', label: "I'm applying from", icon: 'map-marker-outline' },
  { id: '2', label: "I'm going to", icon: 'airplane' },
];

export const destinationData = [
  {
    id: '1',
    name: 'Kazakhstan',
    location: 'Tekergat, Sunamgnj',
    rating: 4.7,
    users: 50,
    image: require('../assets/images/Kazakhstan.png'),
  },
  {
    id: '2',
    name: 'Abu Dhabi',
    location: 'Darma, Kuning',
    rating: 4.5,
    users: 30,
    image: require('../assets/images/Kazakhstan.png'),
  },
];

// export const destinations = [
//   {
//     name: 'Kazakhstan',
//     location: 'Tekergat, Sunamgnj',
//     rating: 4.7,
//     image: require('../assets/kazakhstan.jpg'),
//     users: [
//       require('../assets/user1.png'),
//       require('../assets/user2.png'),
//       require('../assets/user3.png'),
//     ],
//     moreUsers: 50,
//   },
//   // Add more cards if needed...
// ];


export const data = [
    { id: '1', title: 'Tourism' },
    { id: '2', title: 'Business' },
    { id: '3', title: 'Transit' },
    { id: '4', title: 'Medical' },
];

export const Long_data = [
    { id: '1', title: 'Tourism' },
    { id: '2', title: 'Business' },
    { id: '3', title: 'Transit' },
];

export const services = [
  { id: '1', title: 'Doorstep Delivery Services', icon: <Scooter width={scale(54)} height={scale(44)} /> },
  { id: '2', title: 'Automated SMS of Visa Status',icon: <Message width={scale(54)} height={scale(44)}/> },
  { id: '3', title: 'Courier Services',icon: <CourierServices width={scale(54)} height={scale(44)}/> },
  { id: '4', title: 'Travel Insurance',icon: <TravelInsurance width={scale(54)} height={scale(44)}/> },
  { id: '5', title: 'Premium Lounge', icon: <PremiumLounge width={scale(54)} height={scale(44)}/> },
];


// CountriesData.js
export const countries = [
  { label: 'United States', value: 'United States' },
  { label: 'Canada', value: 'Canada' },
  { label: 'United Kingdom', value: 'United Kingdom' },
  { label: 'Australia', value: 'Australia' },
  { label: 'Germany', value: 'Germany' },
  { label: 'France', value: 'France' },
  { label: 'Japan', value: 'Japan' },
  { label: 'China', value: 'China' },
  { label: 'India', value: 'India' },
  { label: 'Brazil', value: 'Brazil' },
  { label: 'Mexico', value: 'Mexico' },
  { label: 'South Africa', value: 'South Africa' },
  { label: 'Argentina', value: 'Argentina' },
  { label: 'Italy', value: 'Italy' },
  { label: 'Spain', value: 'Spain' },
  { label: 'Russia', value: 'Russia' },
  { label: 'Egypt', value: 'Egypt' },
  { label: 'New Zealand', value: 'New Zealand' },
  { label: 'Ireland', value: 'Ireland' },
  { label: 'Netherlands', value: 'Netherlands' },
  { label: 'Sweden', value: 'Sweden' },
  { label: 'Norway', value: 'Norway' },
  { label: 'Denmark', value: 'Denmark' },
  { label: 'Finland', value: 'Finland' },
  { label: 'Switzerland', value: 'Switzerland' },
  { label: 'Austria', value: 'Austria' },
  { label: 'Belgium', value: 'Belgium' },
  { label: 'Greece', value: 'Greece' },
  { label: 'Portugal', value: 'Portugal' },
  { label: 'Turkey', value: 'Turkey' },
  { label: 'South Korea', value: 'South Korea' },
  { label: 'Singapore', value: 'Singapore' },
  { label: 'Malaysia', value: 'Malaysia' },
  { label: 'Thailand', value: 'Thailand' },
  { label: 'Indonesia', value: 'Indonesia' },
  { label: 'Philippines', value: 'Philippines' },
  { label: 'Vietnam', value: 'Vietnam' },
  { label: 'United Arab Emirates', value: 'United Arab Emirates' },
  { label: 'Saudi Arabia', value: 'Saudi Arabia' },
  { label: 'Qatar', value: 'Qatar' },
  { label: 'Kuwait', value: 'Kuwait' },
  { label: 'Israel', value: 'Israel' },
  { label: 'Chile', value: 'Chile' },
  { label: 'Colombia', value: 'Colombia' },
  { label: 'Peru', value: 'Peru' },
  { label: 'Venezuela', value: 'Venezuela' },
  { label: 'Nigeria', value: 'Nigeria' },
  { label: 'Kenya', value: 'Kenya' },
  { label: 'Ethiopia', value: 'Ethiopia' },
  { label: 'Morocco', value: 'Morocco' },
  { label: 'Algeria', value: 'Algeria' },
  { label: 'Pakistan', value: 'Pakistan' },
  { label: 'Bangladesh', value: 'Bangladesh' },
  { label: 'Sri Lanka', value: 'Sri Lanka' },
  { label: 'Nepal', value: 'Nepal' },
  { label: 'Myanmar', value: 'Myanmar' },
  { label: 'Cambodia', value: 'Cambodia' },
  { label: 'Laos', value: 'Laos' },
  { label: 'Mongolia', value: 'Mongolia' },
  { label: 'Kazakhstan', value: 'Kazakhstan' },
  { label: 'Uzbekistan', value: 'Uzbekistan' },
  { label: 'Ukraine', value: 'Ukraine' },
  { label: 'Poland', value: 'Poland' },
  { label: 'Czech Republic', value: 'Czech Republic' },
  { label: 'Hungary', value: 'Hungary' },
  { label: 'Romania', value: 'Romania' },
  { label: 'Bulgaria', value: 'Bulgaria' },
  { label: 'Croatia', value: 'Croatia' },
  { label: 'Serbia', value: 'Serbia' },
  { label: 'Slovakia', value: 'Slovakia' },
  { label: 'Slovenia', value: 'Slovenia' },
  { label: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina' },
  { label: 'North Macedonia', value: 'North Macedonia' },
  { label: 'Albania', value: 'Albania' },
  { label: 'Estonia', value: 'Estonia' },
  { label: 'Latvia', value: 'Latvia' },
  { label: 'Lithuania', value: 'Lithuania' },
  { label: 'Iceland', value: 'Iceland' },
  { label: 'Malta', value: 'Malta' },
  { label: 'Cyprus', value: 'Cyprus' },
  { label: 'Fiji', value: 'Fiji' },
  { label: 'Papua New Guinea', value: 'Papua New Guinea' },
  { label: 'Cuba', value: 'Cuba' },
  { label: 'Jamaica', value: 'Jamaica' },
  { label: 'Dominican Republic', value: 'Dominican Republic' },
  { label: 'Haiti', value: 'Haiti' },
  { label: 'Guatemala', value: 'Guatemala' },
  { label: 'Honduras', value: 'Honduras' },
  { label: 'El Salvador', value: 'El Salvador' },
  { label: 'Nicaragua', value: 'Nicaragua' },
  { label: 'Costa Rica', value: 'Costa Rica' },
  { label: 'Panama', value: 'Panama' },
  { label: 'Puerto Rico', value: 'Puerto Rico' },
  { label: 'Bahamas', value: 'Bahamas' },
  { label: 'Barbados', value: 'Barbados' },
  { label: 'Trinidad and Tobago', value: 'Trinidad and Tobago' },
  { label: 'Saint Lucia', value: 'Saint Lucia' },
  { label: 'Grenada', value: 'Grenada' },
  { label: 'Dominica', value: 'Dominica' },
  { label: 'Antigua and Barbuda', value: 'Antigua and Barbuda' },
  { label: 'Saint Vincent and the Grenadines', value: 'Saint Vincent and the Grenadines' },
  { label: 'Saint Kitts and Nevis', value: 'Saint Kitts and Nevis' },
  { label: 'Maldives', value: 'Maldives' },
  { label: 'Mauritius', value: 'Mauritius' },
  { label: 'Seychelles', value: 'Seychelles' },
  { label: 'Madagascar', value: 'Madagascar' },
  { label: 'Angola', value: 'Angola' },
  { label: 'Mozambique', value: 'Mozambique' },
  { label: 'Zimbabwe', value: 'Zimbabwe' },
  { label: 'Zambia', value: 'Zambia' },
  { label: 'Botswana', value: 'Botswana' },
  { label: 'Namibia', value: 'Namibia' },
  { label: 'Congo (DRC)', value: 'Congo (DRC)' },
  { label: 'Sudan', value: 'Sudan' },
  { label: 'Ghana', value: 'Ghana' },
  { label: 'Côte d\'Ivoire', value: 'Côte d\'Ivoire' },
  { label: 'Cameroon', value: 'Cameroon' },
  { label: 'Senegal', value: 'Senegal' },
  { label: 'Mali', value: 'Mali' },
  { label: 'Niger', value: 'Niger' },
  { label: 'Burkina Faso', value: 'Burkina Faso' },
  { label: 'Chad', value: 'Chad' },
  { label: 'Somalia', value: 'Somalia' },
  { label: 'Eritrea', value: 'Eritrea' },
  { label: 'Djibouti', value: 'Djibouti' },
  { label: 'Comoros', value: 'Comoros' },
  { label: 'Equatorial Guinea', value: 'Equatorial Guinea' },
  { label: 'Gabon', value: 'Gabon' },
  { label: 'Republic of the Congo', value: 'Republic of the Congo' },
  { label: 'Central African Republic', value: 'Central African Republic' },
  { label: 'South Sudan', value: 'South Sudan' },
  { label: 'Lesotho', value: 'Lesotho' },
  { label: 'Eswatini', value: 'Eswatini' }
];
export const boxData = [
  {
    id: '1',
    text: 'Appointment Available',
    IconComponent: ProfileIconBox,
    backgroundColor: '#5cb85c',
    span: 1, // Indicates it takes 1 column (half width)
  },
  {
    id: '2',
    text: 'Appointment Booked',
    IconComponent: ClanderIcon1,
    backgroundColor: '#d9534f',
    span: 1,
  },
  {
    id: '3',
    text: 'Currently Selected Day',
    IconComponent: ClanderIcon2,
    backgroundColor: '#337ab7',
    span: 1,
  },
  {
    id: '4',
    text: 'Weekly Off Day',
    IconComponent: WeeklyIcon,
    backgroundColor: '#6c757d',
    span: 1,
  },
  {
    id: '5',
    text: 'Holiday',
    IconComponent: Holidays,
    backgroundColor: '#f0ad4e',
    span: 2,
  },
];